jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralOtherSymbo$'
  expiration: 36000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bravenewcoin
    password: password
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true